version: "3"
services:
  server1:
    build: server1/
    command: python ./server.py
    ports:
      - 1234:1234
      
  server2:
    build: server2/
    command: python ./server.py
    ports:
      - 1235:1235

  client:
    build: client/
    command: python ./client.py
    network_mode: host
    # stdin_open: true
    tty: true 
    depends_on:
      - server1
      - server2
